# Inspired by https://github.com/Wonderfall/dockerfiles/tree/master/nextcloud#docker-compose-file
version: '3'

services:
  nextcloud:
    image: ghcr.io/hoellen/nextcloud:24
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=system_traefik
      - traefik.http.routers.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.entrypoints=websecure
      - traefik.http.routers.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.tls=true
      - traefik.http.routers.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.tls.certresolver=default
      - traefik.http.routers.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.middlewares=default-security-headers@file
      - traefik.http.services.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.loadbalancer.server.port=8888
      # v1.7
      - traefik.backend=nextcloud
      - traefik.port=8888
      - traefik.default.protocol=http
    links:
      - nextcloud-db:nextcloud-db   # If using MySQL
      - nextcloud-redis:nextcloud-redis # If using Redis
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - ADMIN_USER=admin            # Don't set to configure through browser
      - ADMIN_PASSWORD=admin        # Don't set to configure through browser
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=nextcloud-db
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - default
      - system_traefik
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/nextcloud/config
      - ./apps:/nextcloud/apps2
      - ./logs/php:/php/logs
      - ./logs/nginx:/nginx/logs
      - ./themes:/nextcloud/themes
      - ./php-sessions:/php/session
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nextcloud-db:
    image: mariadb:10.5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nextcloud-redis:
    image: redis:6-alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nextcloud-db-backup:
    image: fradelg/mysql-cron-backup
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    links:
      - nextcloud-db:nextcloud-db
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_USER=root
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MAX_BACKUPS=20
      - CRON_TIME=0 0 * * *
    depends_on:
      - nextcloud-db
    restart: unless-stopped
    volumes:
      - ./mysql-backups:/backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nextcloud-nc-backup:
    image: waja/calcardbackup
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    links:
      - nextcloud-db:nextcloud-db
      - nextcloud:nextcloud
    environment:
      - CRON_TIME=0 0 * * *
      - INIT_BACKUP=yes
      - CALCARD_OPTS=-i -r 20
      - NC_DIR=/nextcloud
      - NC_HOST=nextcloud
      - NC_PORT=8888
      - DB_HOST=nextcloud-db
    depends_on:
      - nextcloud-db
      - nextcloud
    restart: unless-stopped
    volumes:
      - ./calcardbackup:/backup
      - ./config:/nextcloud/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  system_traefik:
    external: true
