# Inspired by https://github.com/Wonderfall/dockerfiles/tree/master/nextcloud#docker-compose-file
services:
  nextcloud:
    image: ${NEXTCLOUD_IMAGE:-ghcr.io/hoellen/nextcloud}:${NEXTCLOUD_VERSION:-32}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=system_traefik
      - traefik.http.routers.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.entrypoints=websecure
      - traefik.http.routers.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.tls=true
      - traefik.http.routers.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.tls.certresolver=default
      - traefik.http.routers.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.middlewares=default-security-headers@file
      - traefik.http.services.${TRAEFIK_PROJECT}-${TRAEFIK_SERVICE_01}-${TRAEFIK_HASH}.loadbalancer.server.port=8888
    links:
      - nextcloud-db:nextcloud-db   # If using MySQL
      - nextcloud-redis:nextcloud-redis # If using Redis
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - ADMIN_USER=admin            # Don't set to configure through browser
      - ADMIN_PASSWORD=admin        # Don't set to configure through browser
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=nextcloud-db
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "8888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - default
      - system_traefik
    restart: unless-stopped
    volumes:
      - ./data/nextcloud/data:/data
      - ./data/nextcloud/config:/nextcloud/config
      - ./data/nextcloud/apps:/nextcloud/apps2
      - ./data/nextcloud/logs/php:/php/logs
      - ./data/nextcloud/logs/nginx:/nginx/logs
      - ./data/nextcloud/themes:/nextcloud/themes
      - ./data/nextcloud/php-sessions:/php/session
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nextcloud-db:
    image: mariadb:10.11
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect" ]
      start_period: 1m
      #start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nextcloud-redis:
    image: redis:8-alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "6379"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./data/redis/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nextcloud-db-backup:
    image: ghcr.io/nfrastack/db-backup:4.9.2
    labels:
      # Allow watchtower to update this image
      - com.centurylinklabs.watchtower.enable=true
    links:
      - nextcloud-db:nextcloud-db
      - nextcloud-redis:nextcloud-redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/db-backups/data:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    restart: unless-stopped
    environment:
      - TIMEZONE=Europe/Berlin
      - CONTAINER_ENABLE_MONITORING=FALSE
      - BACKUP_JOB_CONCURRENCY=1     # Only run one job at a time
      - DEFAULT_CHECKSUM=NONE        # Don't create checksums
      - DEFAULT_COMPRESSION=ZSTD     # Compress all with ZSTD
      - DEFAULT_BACKUP_INTERVAL=1440   # Backup every 1440 minutes
      - DEFAULT_BACKUP_BEGIN=0000      # Start backing up at midnight
      - DEFAULT_CLEANUP_TIME=8640    # Cleanup backups after a week
      - DB01_TYPE=mysql
      - DB01_HOST=nextcloud-db
      - DB01_NAME=nextcloud
      - DB01_USER=nextcloud
      - DB01_PASS=${MYSQL_PASSWORD}
      - DB01_BACKUP_BEGIN=+1
      - DB02_TYPE=redis
      - DB02_HOST=nextcloud-redis
      - DB02_BACKUP_BEGIN=+1
  nextcloud-nc-backup:
    image: waja/calcardbackup
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    links:
      - nextcloud-db:nextcloud-db
      - nextcloud:nextcloud
    environment:
      - CRON_TIME=0 0 * * *
      - INIT_BACKUP=yes
      - CALCARD_OPTS=-i -r 20
      - NC_DIR=/nextcloud
      - NC_HOST=nextcloud
      - NC_PORT=8888
      - DB_HOST=nextcloud-db
      - MARIADB_SSL_SKIP=true
    depends_on:
      - nextcloud-db
      - nextcloud
    restart: unless-stopped
    volumes:
      - ./data/calcardbackup/data:/backup
      - ./data/nextcloud/config:/nextcloud/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  system_traefik:
    external: true
